# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "export PATH=\"$HOME/.local/bin:$PATH\"" >> $GITHUB_ENV  # Trwałe dodanie PATH do zmiennej środowiskowej
    - name: Install requirements
      working-directory: ./example-app
      run: |
        poetry install --no-root
    - name: Test with pytest
      run: |
        poetry run pytest  # Używamy `poetry` do uruchamiania testów

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Lint with flake8
        run: |
          poetry run task lint  # Używamy `poetry` do lintowania

  formatter:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run formatter
        run: |
          poetry run task formatter  # Używamy `poetry` do formatowania

  security:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run security checks
        run: |
          poetry run task security  # Używamy `poetry` do uruchamiania sprawdzania bezpieczeństwa

  unittests:
    needs: [lint, formatter, security]
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        run: poetry run pytest  # Uruchamiamy testy jednostkowe przy użyciu `poetry`
