name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "export PATH=\"$HOME/.local/bin:$PATH\"" >> $GITHUB_ENV 
    - name: Verify Poetry installation
      run: |
        echo $PATH
        which poetry  # Sprawdź, czy poetry jest w PATH
        poetry --version 
    - name: Install requirements
      working-directory: ./example-app 
      run: |
        poetry install --no-root  
    - name: Test with pytest
      working-directory: ./example-app 
      run: |
        poetry run pytest  

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Lint with flake8 
        run: |
          poetry run task lint

  formatter:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run formatter
        working-directory: example-app 
        run: |
          poetry run task formatter

  security:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run security checks
        working-directory: example-app 
        run: |
          poetry run task security


  unittests:
    needs: [lint, formatter, security]
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        working-directory: example-app 
        run: |
          poetry run pytest
